// <auto-generated />
using System;
using GoogleForms.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoogleForms.DAL.Migrations
{
    [DbContext(typeof(GoogleFormsContext))]
    [Migration("20220831110454_deneme121")]
    partial class deneme121
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GoogleForms.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItTrueAnswer")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfChoose")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("answerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8037),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8038),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8038),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8039),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8039),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8040),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 2,
                            answerType = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8041),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 3,
                            answerType = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8041),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 4,
                            answerType = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8042),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 4,
                            answerType = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8042),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 4,
                            answerType = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8043),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 4,
                            answerType = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(8044),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            IsItTrueAnswer = false,
                            NumberOfChoose = 0,
                            QuestionId = 4,
                            answerType = 0
                        });
                });

            modelBuilder.Entity("GoogleForms.Entities.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(7847),
                            FormDescription = "Deneme Formu Açıklaması1",
                            FormTitle = "Deneme Formu Başlığı2",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(7862),
                            FormDescription = "Deneme Formu Açıklaması2",
                            FormTitle = "Deneme Formu Başlığı2",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GoogleForms.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("AverageAnswersValue")
                        .HasColumnType("float");

                    b.Property<double?>("AverageOfAllAnswers")
                        .HasColumnType("float");

                    b.Property<double?>("CorrectAnswerAverage")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxAnsweresValue")
                        .HasColumnType("float");

                    b.Property<double?>("MaxChoiceAnsweresValue")
                        .HasColumnType("float");

                    b.Property<double?>("MinAnsweresValue")
                        .HasColumnType("float");

                    b.Property<double?>("MinChoiceAnsweresValue")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfAnswers")
                        .HasColumnType("int");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<double?>("WrongAnswerAverage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(7982),
                            FormId = 1,
                            IsDeleted = false,
                            IsRequired = false,
                            NumberOfAnswers = 0,
                            QuestionTitle = "Deneme Sorusu1 ",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(7983),
                            FormId = 1,
                            IsDeleted = false,
                            IsRequired = false,
                            NumberOfAnswers = 0,
                            QuestionTitle = "Deneme Sorusu1 ",
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(7984),
                            FormId = 2,
                            IsDeleted = false,
                            IsRequired = false,
                            NumberOfAnswers = 0,
                            QuestionTitle = "Deneme Sorusu1 ",
                            QuestionType = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 8, 31, 14, 4, 53, 936, DateTimeKind.Local).AddTicks(7984),
                            FormId = 2,
                            IsDeleted = false,
                            IsRequired = false,
                            NumberOfAnswers = 0,
                            QuestionTitle = "Deneme Sorusu1 ",
                            QuestionType = 3
                        });
                });

            modelBuilder.Entity("GoogleForms.Entities.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItTrueAnswer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfChoose")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("answerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserAnswer");
                });

            modelBuilder.Entity("GoogleForms.Entities.Answer", b =>
                {
                    b.HasOne("GoogleForms.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GoogleForms.Entities.Question", b =>
                {
                    b.HasOne("GoogleForms.Entities.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("GoogleForms.Entities.UserAnswer", b =>
                {
                    b.HasOne("GoogleForms.Entities.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GoogleForms.Entities.Form", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GoogleForms.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
