// <auto-generated />
using System;
using GoogleForms.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoogleForms.DAL.Migrations
{
    [DbContext(typeof(GoogleFormsContext))]
    [Migration("20220819061039_deneme798")]
    partial class deneme798
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GoogleForms.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("answerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3151),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3154),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3155),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3155),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3156),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 1,
                            answerType = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3218),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 2,
                            answerType = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3219),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 3,
                            answerType = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3219),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 4,
                            answerType = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3220),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 4,
                            answerType = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3221),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 4,
                            answerType = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3222),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 4,
                            answerType = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3223),
                            Description = "Deneme Cevabı 1",
                            IsDeleted = false,
                            QuestionId = 4,
                            answerType = 0
                        });
                });

            modelBuilder.Entity("GoogleForms.Entities.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(2936),
                            FormDescription = "Deneme Formu Açıklaması1",
                            FormTitle = "Deneme Formu Başlığı2",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(2947),
                            FormDescription = "Deneme Formu Açıklaması2",
                            FormTitle = "Deneme Formu Başlığı2",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GoogleForms.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3092),
                            FormId = 1,
                            IsDeleted = false,
                            IsRequired = false,
                            QuestionTitle = "Deneme Sorusu1 ",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3095),
                            FormId = 1,
                            IsDeleted = false,
                            IsRequired = false,
                            QuestionTitle = "Deneme Sorusu1 ",
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3096),
                            FormId = 2,
                            IsDeleted = false,
                            IsRequired = false,
                            QuestionTitle = "Deneme Sorusu1 ",
                            QuestionType = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 8, 19, 9, 10, 38, 751, DateTimeKind.Local).AddTicks(3096),
                            FormId = 2,
                            IsDeleted = false,
                            IsRequired = false,
                            QuestionTitle = "Deneme Sorusu1 ",
                            QuestionType = 3
                        });
                });

            modelBuilder.Entity("GoogleForms.Entities.Answer", b =>
                {
                    b.HasOne("GoogleForms.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GoogleForms.Entities.Question", b =>
                {
                    b.HasOne("GoogleForms.Entities.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("GoogleForms.Entities.Form", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GoogleForms.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
